version: '2.3'

services:
  tests:
    image: directai/directai:testing
    working_dir: /obfuscated_tests
    command: python -m unittest tests/test.py
    container_name: local_streaming_tests
    networks:
      - deploy_network
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  deploy_network:
    driver: bridge